### ISSUE TITLE
Not really an issue, but a question

### ISSUE THREAD

**Issue by lynxtdc** [shiftonelabs/laravel-db-events#1]
Can your package be used to change between database connections dynamically?

**Comment by patrickcarlohickman** [comment]
In a roundabout way.

In the `DatabaseConnecting` event, you have access to modify the config that is used to connect to the database, so you can replace the entire config array with the config from another connection.

For example, if your default connection is `mysql1`, and you'd like to use the event to connect to `mysql2` instead:

``` php
app('events')->listen('ShiftOneLabs\LaravelDbEvents\Extension\Database\Events\DatabaseConnecting', function ($event) {
    $event->config = config('database.connections.mysql2');
});
```

However, the main restriction to this method is that the event is fired from inside the `Connector` that has already been determined by the `driver` config value. Therefore, changing the `driver` config value inside the event will not have any effect. 

For example, given the following configuration:

``` php
    'connections' => [
        'sqlite' => [
            'driver' => 'sqlite',
            'database' => ':memory:',
        ],
        'mysql1' => [
            'driver' => 'mysql',
            // mysql1 config
        ],
        'mysql2' => [
            'driver' => 'mysql',
            // mysql2 config
        ],
    ],
```

If your connection is `sqlite` and you to switch to `mysql1`, that won't work since the drivers are different. The event is fired within the `SqliteConnector`, so you will be attempting to connect to the `mysql` database using the `sqlite` driver. However, if you would like to switch between `mysql1` and `mysql2`, that should work fine.

**Comment by lynxtdc** [comment]
Beautiful! I am looking to switch mysql connections dynamically. Thanks!
